apiVersion: apps/v1
kind: Deployment
metadata:
  name: heart-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: heart-api
  template:
    metadata:
      labels:
        app: heart-api
    spec:
      containers:
        - name: heart-api
          image: ghcr.io/2024aa05857-hub/heart-uci-mlops:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
